export const SKILLS = [
  {
    key: 'gwa-autofill',
    path: '/gwa-autofill',
    icon: '💧',
    name: 'GWA Calculator Autofill',
    description: 'Auto-extract and compute Level 1 GWA Yield Calculator inputs (C14-C38) from NS well logs, pumping tests, chemistry, and climate data.',
    type: 'deterministic',
  },
  {
    key: 'gwa-report',
    path: '/gwa-report',
    icon: '📄',
    name: 'GWA Level 1 Report',
    description: 'Draft a full NSECC-compliant Level 1 Groundwater Assessment report from calculator outputs and site context.',
    type: 'llm',
  },
  {
    key: 'helio-report',
    path: '/helio-report',
    icon: '🏗️',
    name: 'Helio Pre-Dev Report',
    description: 'Assemble a Pre-Development Site Assessment report from a zip of GIS research and architectural drawings.',
    type: 'llm',
  },
  {
    key: 'helio-tiers',
    path: '/helio-tiers',
    icon: '📊',
    name: 'Helio Feasibility Tiers',
    description: 'Assemble a tiered feasibility report — Basic scorecard, Detailed write-up, or Comprehensive assessment.',
    type: 'llm',
  },
  {
    key: 'html-populator',
    path: '/html-populator',
    icon: '🧩',
    name: 'HTML Layout Card Populator',
    description: 'Populate the parcelinfo, Environmental, and Utilities QGIS layout HTML cards from a plain key:value data file.',
    type: 'deterministic',
  },
  {
    key: 'land-use-prompt',
    path: '/land-use-prompt',
    icon: '📝',
    name: 'Land Use Prompt Builder',
    description: 'Extract fields from uploaded planning documents and rebuild the standardized Land Use Feasibility Report prompt.',
    type: 'llm',
  },
]
